# -*- coding: utf-8 -*-
"""simejadrijev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZgQJlR_K5gUnte-bwCSaX1zOOSWqCJn
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# 1. Učitaj podatke
data = pd.read_csv("sample_data/07_production_defects.csv")


# 2. Definiraj varijable
X = data[["production_time"]]  # mora biti 2D
y = data["defects"]

# 3. Kreiraj i treniraj model
model = LinearRegression()
model.fit(X, y)

# 4. Predviđanja
y_pred = model.predict(X)

# 5. Ispiši rezultate
print(f"Jednadžba regresije: defects = {model.coef_[0]:.4f} * production_time + {model.intercept_:.4f}")
print(f"R² score: {r2_score(y, y_pred):.4f}")

# 6. Nacrtaj graf
plt.scatter(X, y, color='blue', label='Stvarni podaci')
plt.plot(X, y_pred, color='red', label='Linearni model')
plt.xlabel('Production Time')
plt.ylabel('Defects')
plt.title('Linearna regresija: Production Time vs Defects')
plt.legend()
plt.show()