# -*- coding: utf-8 -*-
"""smachiedo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GSGpbyV98Okeq8Hj2iiIfaihblK8K6m9
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd '/content/drive/MyDrive/Colab Notebooks/ZP'

import pandas as pd
from sklearn.linear_model import LinearRegression
df = pd.read_csv('19_electricity_usage.csv')

x = df[['household_size']]
y = df['electricity_usage']
model = LinearRegression().fit(x, y)

# Example prediction for a household size of 4
household = 4
prediction = model.predict([[household]])
print(f"Estimated electricity usage for a household size of {household}: {prediction[0]:.2f}")



import matplotlib.pyplot as plt
import numpy as np

# Create a scatter plot of the original data
plt.scatter(x, y, label='Data')

# Generate points for the regression line
x_line = np.linspace(x.min(), x.max(), 100).reshape(-1, 1)
y_line = model.predict(x_line)

# Plot the regression line
plt.plot(x_line, y_line, color='red', label='Linear Regression Fit')

# Add labels and title
plt.xlabel('Household Size')
plt.ylabel('Electricity Usage')
plt.title('Electricity Usage vs. Household Size with Linear Regression Fit')
plt.legend()
plt.grid(True)
plt.show()

