# -*- coding: utf-8 -*-
"""ZP_tlak_mkar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1na3_v0xsfGfzG8CcFniJBckQ59IKpIVi
"""

file_=open('14_blood_pressure.csv')

import pandas as pd
df = pd.read_csv(file_)
print(df)

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

X = df[["age"]]
y = df[["blood_pressure"]]

regressor = LinearRegression()
regressor.fit(X, y)

y_pred = regressor.predict(X)

plt.scatter(X, y, color = 'red')
plt.plot(X, regressor.predict(X), color = 'blue')
plt.title('godine i tlak')
plt.xlabel('godine')
plt.ylabel('tlak')
plt.show()