{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "CFTDWeBfPWGA"
      },
      "outputs": [],
      "source": [
        "import marimo\n",
        "\n",
        "app = marimo.App(width=\"medium\")\n",
        "\n",
        "@app.cell\n",
        "def _():\n",
        "    # Import necessary libraries for data manipulation, visualization, and machine learning.\n",
        "    import pandas as pd\n",
        "    import numpy as np\n",
        "    import matplotlib.pyplot as plt\n",
        "    import seaborn as sns\n",
        "    from IPython.display import display # Explicitly import display for clear output\n",
        "\n",
        "    from sklearn.model_selection import train_test_split\n",
        "    from sklearn.linear_model import LinearRegression\n",
        "    from sklearn.preprocessing import StandardScaler\n",
        "    from sklearn import metrics\n",
        "    return (\n",
        "        LinearRegression,\n",
        "        StandardScaler,\n",
        "        metrics,\n",
        "        pd,\n",
        "        plt,\n",
        "        sns,\n",
        "        train_test_split,\n",
        "        display # Return display as well if it's used explicitly\n",
        "    )\n",
        "\n",
        "@app.cell\n",
        "def _(pd):\n",
        "    # Load the marketing dataset\n",
        "    # The dataset contains information about advertising spending (TV, Radio, Newspaper) and Sales.\n",
        "    marketing_data = pd.read_csv(\"/workspaces/2025-sci-prog/labs/03/marketing.csv\")\n",
        "    print(\"First 5 rows of the dataset:\")\n",
        "    display(marketing_data.head()) # Use display for explicit output\n",
        "    return (marketing_data,)\n",
        "\n",
        "@app.cell\n",
        "def _(marketing_data):\n",
        "    # Check for any missing values in the dataset\n",
        "    print(\"Missing values per column:\")\n",
        "    display(marketing_data.isna().sum())\n",
        "    return\n",
        "\n",
        "@app.cell\n",
        "def _(marketing_data):\n",
        "    # Check for duplicate rows in the dataset\n",
        "    print(\"Number of duplicate rows:\")\n",
        "    display(marketing_data.duplicated().sum())\n",
        "    return\n",
        "\n",
        "@app.cell\n",
        "def _(marketing_data, sns, plt):\n",
        "    # Calculate the correlation matrix to understand relationships between variables\n",
        "    correlation_matrix = marketing_data.corr()\n",
        "\n",
        "    # Visualize the correlation matrix using a heatmap\n",
        "    plt.figure(figsize=(8, 6))\n",
        "    sns.heatmap(data=correlation_matrix, annot=True, cmap='coolwarm', fmt=\".2f\")\n",
        "    plt.title('Correlation Matrix of Marketing Data')\n",
        "    plt.show()\n",
        "    return\n",
        "\n",
        "@app.cell\n",
        "def _(StandardScaler, marketing_data, train_test_split):\n",
        "    # Define features (X) and target (y)\n",
        "    X = marketing_data[['TV', 'Radio', 'Newspaper']]\n",
        "    y = marketing_data['Sales']\n",
        "\n",
        "    # Split the data into training and testing sets\n",
        "    X_train, X_test, y_train, y_test = train_test_split(\n",
        "        X, y, random_state=42, test_size=0.25\n",
        "    )\n",
        "\n",
        "    # Scale the features using StandardScaler\n",
        "    feature_scaler = StandardScaler()\n",
        "    X_train_scaled = feature_scaler.fit_transform(X_train)\n",
        "    X_test_scaled = feature_scaler.fit_transform(X_test)\n",
        "    return X_test_scaled, X_train_scaled, y_test, y_train\n",
        "\n",
        "@app.cell\n",
        "def _(LinearRegression, X_train_scaled, y_train):\n",
        "    # Initialize and train the Linear Regression model\n",
        "    linear_reg_model = LinearRegression()\n",
        "    linear_reg_model.fit(X_train_scaled, y_train)\n",
        "    print(\"Linear Regression Model Trained Successfully.\")\n",
        "    return (linear_reg_model,)\n",
        "\n",
        "@app.cell\n",
        "def _(X_test_scaled, linear_reg_model):\n",
        "    # Make predictions on the scaled test set\n",
        "    y_predicted = linear_reg_model.predict(X_test_scaled)\n",
        "    return (y_predicted,)\n",
        "\n",
        "@app.cell\n",
        "def _(metrics, y_predicted, y_test):\n",
        "    # Evaluate the model's performance using various regression metrics\n",
        "    mae = metrics.mean_absolute_error(y_test, y_predicted)\n",
        "    mse = metrics.mean_squared_error(y_test, y_predicted)\n",
        "    rmse = metrics.root_mean_squared_error(y_test, y_predicted)\n",
        "    r2_score_val = metrics.r2_score(y_test, y_predicted)\n",
        "\n",
        "    print(f\"Model Performance Metrics:\")\n",
        "    print(f\"  Mean Absolute Error (MAE): {mae:.2f}\")\n",
        "    print(f\"  Mean Squared Error (MSE): {mse:.2f}\")\n",
        "    print(f\"  Root Mean Squared Error (RMSE): {rmse:.2f}\")\n",
        "    print(f\"  R-squared (R2 Score): {r2_score_val:.2f}\")\n",
        "    return\n",
        "\n",
        "@app.cell\n",
        "def _(plt, y_predicted, y_test):\n",
        "    # Visualize actual vs. predicted sales\n",
        "    plt.figure(figsize=(10, 7))\n",
        "    plt.scatter(y_test, y_predicted, alpha=0.7, edgecolors='k', label='Actual vs. Predicted Sales')\n",
        "    plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2, label='Perfect Prediction Line')\n",
        "    plt.xlabel(\"Actual Sales (Prodaja)\")\n",
        "    plt.ylabel(\"Predicted Sales (Predvidanje)\")\n",
        "    plt.title(\"Comparison of Actual vs. Predicted Sales\")\n",
        "    plt.legend()\n",
        "    plt.grid(True)\n",
        "    plt.tight_layout()\n",
        "    plt.show()\n",
        "    return\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    app.run()"
      ]
    }
  ]
}