# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ImyQ3CFZBkbQBwnP_NhotUk0CCsSSaRI
"""

import marimo

# Initialize the Marimo application with a medium width
app = marimo.App(width="medium")

@app.cell
def _():
    # Import standard libraries for file system, environment variables, and HTTP requests
    import os
    import requests
    from dotenv import load_dotenv
    from pathlib import Path

    # Import libraries for HTML parsing and Google Gemini API interaction
    from bs4 import BeautifulSoup
    from google import genai

    # Return all imported modules and functions that will be used by other cells
    return BeautifulSoup, Path, genai, load_dotenv, os, requests


@app.cell
def _(Path, load_dotenv, os):
    # Determine the script's folder path to locate the .env file
    # Note: In Colab, Path(__file__) might not work directly. Adjust if running locally.
    # For Colab, you might need to manually set environment variables or upload a .env file.
    # For demonstration, assuming a .env file exists in the expected path or keys are set.

    try:
        script_folder = Path(__file__).parent
        dotenv_path = script_folder / ".env"
        load_dotenv(dotenv_path=dotenv_path) # Load API keys from .env file
    except NameError:
        # Fallback for environments where __file__ is not defined (e.g., some interactive sessions)
        print("Warning: Could not determine script path for .env. Ensure API keys are set as environment variables.")
        load_dotenv() # Load from default locations or already set env vars

    # Retrieve API keys from environment variables
    STEEL_API_KEY = os.getenv("steel_api")
    GEMINI_API_KEY = os.getenv("google_api")

    # Define the URL for scraping (The Guardian Europe section as requested)
    TARGET_URL = "https://www.theguardian.com/europe"

    # Basic validation for API keys (optional but good practice)
    if not STEEL_API_KEY:
        print("Error: STEEL_API_KEY not found in environment variables.")
    if not GEMINI_API_KEY:
        print("Error: GEMINI_API_KEY not found in environment variables.")

    return GEMINI_API_KEY, STEEL_API_KEY, TARGET_URL


@app.cell
def _(STEEL_API_KEY, TARGET_URL, requests):
    # Configure the payload for the Steel API web scraping request
    scrape_payload = {
        "url": TARGET_URL,
        "format": ["html"],
        "screenshot": False,
        "pdf": False,
        "delay": 2, # Increased delay slightly for politeness
        "useProxy": True, # Using proxy for more reliable scraping
        "region": "eu" # Specify region for proxy
    }

    # Set headers including the Steel API key for authentication
    request_headers = {
        "Content-Type": "application/json",
        "steel-api-key": STEEL_API_KEY
    }

    raw_guardian_html = "" # Initialize raw HTML content
    try:
        # Send the scraping request to Steel API
        response = requests.post(
            "https://api.steel.dev/v1/scrape", headers=request_headers, json=scrape_payload
        )
        response.raise_for_status() # Raise HTTPError for bad responses (4xx or 5xx)

        # Parse the JSON response and extract the HTML content
        scraped_data = response.json()
        raw_guardian_html = scraped_data["content"]["html"]
        print(f"Successfully scraped HTML from {TARGET_URL}")
        # print("\n--- Start of Scraped HTML (truncated for brevity) ---")
        # print(raw_guardian_html[:500] + "...") # Print a snippet for verification
        # print("\n--- End of Scraped HTML ---")

    except requests.exceptions.RequestException as e:
        print(f"Error during web scraping: {e}")
        if response is not None:
            print(f"Response text: {response.text}")
    except KeyError:
        print("Error: 'content' or 'html' key not found in Steel API response.")

    return (raw_guardian_html,)


@app.cell
def _(BeautifulSoup, raw_guardian_html):
    # Parse the raw HTML content using BeautifulSoup
    soup = BeautifulSoup(raw_guardian_html, "html.parser")

    # --- New Logic: Extracting Guardian News Article Information ---
    # The Guardian's structure can vary, but we'll target common elements for headlines and links.
    # This is a robust approach, looking for `h3` elements that often contain article titles,
    # and then finding their parent `a` tags for the link.

    extracted_news_items = []
    # Find all h3 tags that likely contain article titles
    headlines = soup.find_all('h3')

    for headline_tag in headlines:
        # Look for an 'a' (anchor) tag within or as a parent of the headline_tag
        link_tag = headline_tag.find('a', href=True) or headline_tag.find_parent('a', href=True)

        if link_tag and link_tag.text.strip():
            title = link_tag.text.strip()
            url = link_tag['href']
            # Filter out non-article links if necessary (e.g., navigation, sections)
            if '/article/' in url or '/commentisfree/' in url or '/world/' in url or '/uk-news/' in url: # Heuristic filtering
                extracted_news_items.append({"title": title, "url": url})

    print(f"Found {len(extracted_news_items)} potential news articles.")
    if extracted_news_items:
        print("First 3 extracted articles:")
        for i, item in enumerate(extracted_news_items[:3]):
            print(f"  {i+1}. Title: {item['title']}\n     URL: {item['url']}")
    else:
        print("No news articles found with the specified selectors. The Guardian's structure might have changed.")

    return (extracted_news_items,)


@app.cell
def _(extracted_news_items, genai, GEMINI_API_KEY):
    # Initialize the Google Gemini client with the API key
    client = genai.Client(api_key=GEMINI_API_KEY)

    # Construct the prompt for Gemini to analyze the scraped news articles
    gemini_prompt = "Please analyze the following news articles from The Guardian. For each article, provide a brief summary and identify the main topic. Then, provide an overall summary of the themes prevalent in today's European news as per these articles.\n\n"

    if not extracted_news_items:
        gemini_prompt += "No articles were provided for analysis."
    else:
        # Iterate through the extracted news items and add them to the prompt
        for i, article in enumerate(extracted_news_items):
            gemini_prompt += f"Article {i+1}:\nTitle: {article['title']}\nURL: {article['url']}\n---\n"
            if i >= 10: # Limit the number of articles sent to Gemini to avoid excessively long prompts
                gemini_prompt += f"... (and {len(extracted_news_items) - i - 1} more articles)"
                break

    print("Sending request to Gemini API...")
    try:
        # Generate content using the Gemini model
        gemini_response = client.models.generate_content(
            model="gemini-2.5-flash", # Using a fast, cost-effective model
            contents=gemini_prompt
        )

        # Print the analysis provided by Gemini
        print("\n--- Gemini's News Analysis ---")
        print(gemini_response.text)
        print("\n----------------------------")

    except Exception as e:
        print(f"Error interacting with Gemini API: {e}")
        print("Please ensure your GEMINI_API_KEY is valid and sufficient for the model.")
    return


if __name__ == "__main__":
    app.run()